In [2]:
import numpy as np
import pandas as pd

In [3]:
news = pd.read_csv("data/raw/news.tsv", sep="\t", header=None)
behaviors = pd.read_csv("data/raw/behaviors.tsv", sep="\t", header=None)
# behaviors.columns = ["impression_id", "user_id", "time", "history", "impressions"]

In [4]:
news.head()

,0,1,2,3,4,5,6,7
0,N55528,lifestyle,lifestyleroyals,"The Brands Queen Elizabeth, Prince Charles, an...","Shop the notebooks, jackets, and more that the...",https://assets.msn.com/labs/mind/AAGH0ET.html,"[{""Label"": ""Prince Philip, Duke of Edinburgh"",...",[]
1,N19639,health,weightloss,50 Worst Habits For Belly Fat,These seemingly harmless habits are holding yo...,https://assets.msn.com/labs/mind/AAB19MK.html,"[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik...","[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik..."
2,N61837,news,newsworld,The Cost of Trump's Aid Freeze in the Trenches...,Lt. Ivan Molchanets peeked over a parapet of s...,https://assets.msn.com/labs/mind/AAJgNsz.html,[],"[{""Label"": ""Ukraine"", ""Type"": ""G"", ""WikidataId..."
3,N53526,health,voices,I Was An NBA Wife. Here's How It Affected My M...,"I felt like I was a fraud, and being an NBA wi...",https://assets.msn.com/labs/mind/AACk2N6.html,[],"[{""Label"": ""National Basketball Association"", ..."
4,N38324,health,medical,"How to Get Rid of Skin Tags, According to a De...","They seem harmless, but there's a very good re...",https://assets.msn.com/labs/mind/AAAKEkt.html,"[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI...","[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI..."

In [5]:
news[7].head(
)

0                                                   []
1    [{"Label": "Adipose tissue", "Type": "C", "Wik...
2    [{"Label": "Ukraine", "Type": "G", "WikidataId...
3    [{"Label": "National Basketball Association", ...
4    [{"Label": "Skin tag", "Type": "C", "WikidataI...
Name: 7, dtype: object

In [6]:
behaviors.head()

,0,1,2,3,4
0,1,U13740,11/11/2019 9:05:58 AM,N55189 N42782 N34694 N45794 N18445 N63302 N104...,N55689-1 N35729-0
1,2,U91836,11/12/2019 6:11:30 PM,N31739 N6072 N63045 N23979 N35656 N43353 N8129...,N20678-0 N39317-0 N58114-0 N20495-0 N42977-0 N...
2,3,U73700,11/14/2019 7:01:48 AM,N10732 N25792 N7563 N21087 N41087 N5445 N60384...,N50014-0 N23877-0 N35389-0 N49712-0 N16844-0 N...
3,4,U34670,11/11/2019 5:28:05 AM,N45729 N2203 N871 N53880 N41375 N43142 N33013 ...,N35729-0 N33632-0 N49685-1 N27581-0
4,5,U8125,11/12/2019 4:11:21 PM,N10078 N56514 N14904 N33740,N39985-0 N36050-0 N16096-0 N8400-1 N22407-0 N6...

In [7]:
news.columns = ["news_id", "category", "subcategory", "title", "abstract", "url", "title_entities", "abstract_entities"]
behaviors.columns = ["impression_id", "user_id", "time", "history", "impressions"]

In [8]:
print(behaviors.head())

   impression_id user_id                   time  \
0              1  U13740  11/11/2019 9:05:58 AM
1              2  U91836  11/12/2019 6:11:30 PM
2              3  U73700  11/14/2019 7:01:48 AM
3              4  U34670  11/11/2019 5:28:05 AM
4              5   U8125  11/12/2019 4:11:21 PM

                                             history  \
0  N55189 N42782 N34694 N45794 N18445 N63302 N104...
1  N31739 N6072 N63045 N23979 N35656 N43353 N8129...
2  N10732 N25792 N7563 N21087 N41087 N5445 N60384...
3  N45729 N2203 N871 N53880 N41375 N43142 N33013 ...
4                        N10078 N56514 N14904 N33740

                                         impressions
0                                  N55689-1 N35729-0
1  N20678-0 N39317-0 N58114-0 N20495-0 N42977-0 N...
2  N50014-0 N23877-0 N35389-0 N49712-0 N16844-0 N...
3                N35729-0 N33632-0 N49685-1 N27581-0
4  N39985-0 N36050-0 N16096-0 N8400-1 N22407-0 N6...

In [9]:
news["category"].unique()

array(['lifestyle', 'health', 'news', 'sports', 'weather',
       'entertainment', 'autos', 'travel', 'foodanddrink', 'tv',
       'finance', 'movies', 'video', 'music', 'kids', 'middleeast',
       'northamerica'], dtype=object)

In [10]:
news["subcategory"].unique()

array(['lifestyleroyals', 'weightloss', 'newsworld', 'voices', 'medical',
       'football_nfl', 'weathertopstories', 'gaming',
       'newsscienceandtechnology', 'nutrition', 'autosenthusiasts',
       'wellness', 'health-news', 'celebrity', 'travelarticle',
       'autossuvs', 'newspolitics', 'traveltripideas', 'autosnews',
       'newsbusiness', 'golf', 'lifestylepetsanimals', 'recipes',
       'tv-gallery', 'basketball_nba', 'lifestylebuzz', 'shop-all',
       'newsphotos', 'basketball_ncaa', 'finance-real-estate',
       'quickandeasy', 'tv-celebrity', 'travelnews', 'movies-gallery',
       'tipsandtricks', 'autosbuying', 'more_sports', 'shop-apparel',
       'autostrucks', 'lifestyledidyouknow', 'racing', 'newstrends',
       'restaurantsandnews', 'lifestylemindandsoul', 'baseball_mlb',
       'finance-saving-investing', 'viral', 'finance-taxes',
       'lifestylebeauty', 'newsopinion', 'finance-companies',
       'lifestyleshopping', 'finance-savemoney', 'mentalhealth', 'newsus',
       'lifestylesmartliving', 'fitness', 'autosclassics', 'news',
       'finance-career', 'lifestylehoroscope', 'newsgoodnews',
       'football_ncaa', 'retirement', 'lifestylehomeandgarden',
       'ads-lung-health', 'personalfinance', 'finance-top-stocks',
       'musicnews', 'causes', 'newsoffbeat', 'tennis', 'videos',
       'weight-loss', 'lifestylecareer', 'animals', 'markets',
       'shop-holidays', 'financenews', 'movievideo', 'finance-retirement',
       'mma', 'finance-career-education', 'movies-celebrity',
       'lifestyledecor', 'finance-billstopay', 'lifestylecelebstyle',
       'newscrime', 'newsweather', 'popculture', 'lifestyleweddings',
       'beverages', 'lifestylefamilyandrelationships', 'music-gallery',
       'entertainment-celebrity', 'foodnews', 'musicvideos',
       'entertainment-books', 'healthagingwell', 'tvnews', 'video',
       'lifestylelovesex', 'causes-green-living',
       'lifestylecleaningandorganizing', 'autosmotorcycles',
       'autosresearchguides', 'football_nfl_videos', 'advice',
       'factcheck', 'lifestyleparenting', 'soccer', 'outdoors',
       'music-celebrity', 'baseball_mlb_videos', 'lifestylediy',
       'science', 'traveltips', 'lifestylepets', 'travel-videos',
       'shop-home-goods', 'newsfactcheck', 'autossports', 'autosluxury',
       'travel-points-rewards', 'humor', 'autossema', 'movienews', 'fun',
       'peopleandplaces', 'foodrecipes', 'football_ncaa_videos',
       'icehockey_nhl', 'lifestylevideo', 'holidays',
       'finance-healthcare', 'music-awards', 'seasonal', 'hollywood',
       'autosownership', 'lifestyle', 'finance-small-business',
       'tv-recaps', 'lifestylefamily', 'finance-video', 'boxing-mma',
       'tvvideos', 'autosreview', 'causes-animals', 'finance-technology',
       'finance-home-loans', 'lifestylefashion', 'autosvideonew',
       'boxing', 'games', 'relationships', 'lifestylerelationships',
       'causes-food-insecurity', 'autoscartech', 'movies-oscars',
       'autoshybrids', 'celebritynews', 'autostokyo', 'elections-2020-us',
       'finance-insurance', 'healthnews', 'soccer_mls', 'causes-poverty',
       'music-grammys', 'lifestyle-wedding', 'music-reviews',
       'autosresearch', 'pregnancyparenting', 'career-news',
       'newsscience', 'reviews', 'basketball_ncaa_videos', 'autoscompact',
       'finance-credit', 'lifestyle-news-feature', 'finance-education',
       'soccer_epl', 'finance-insidetheticker', 'olympics-videos',
       'awards', 'basketball_wnba', 'golfvideos', 'autosvans',
       'sports_news', 'wines', 'autospassenger', 'middleeast-top-stories',
       'causes-environment', 'cocktails', 'newstvmedia', 'tunedin',
       'ads-latingrammys', 'travel-adventure-travel', 'cookingschool',
       'mmaufc', 'tv-reviews', 'technologyinvesting',
       'narendramodi_opinion', 'lifestylemarriage',
       'finance-homesandpropertysection', 'tv', 'cooking', 'newsnational',
       'halloween', 'movies-awards', 'people-places', 'awardstyle',
       'basketball_nba_videos', 'empowering-the-planet', 'company-news',
       'newsworldpolitics', 'othersports', 'yearinoffbeatgoodnews',
       'newsrealestate', 'lifestyleshoppinghomegarden', 'sports',
       'photos', 'downtime', 'finance-mutual-funds', 'cma-awards',
       'newsvideo', 'travel', 'lifestylehoroscopefish', 'baseball',
       'topnews', 'wonder', 'newsother', 'foodtips', 'tv-golden-globes',
       'autosvideos', 'causes-disaster-relief', 'finance-auto-insurance',
       'weatherfullscreenmaps', 'causes-military-appreciation', 'indepth',
       'healthyliving', 'lifestylewhatshot', 'lifestylestyle',
       'shop-books-movies-tv', 'health-cancer', 'strength',
       'newselection2020', 'finance-startinvesting',
       'spendingandborrowing', 'ustravel', 'internationaltravel',
       'traveltrivia', 'cardio', 'comedy', 'soccer_bund', 'watch',
       'tv-golden-globes-video', 'foodanddrink', 'tennis_intl',
       'entertainmentmusic', 'northamerica-video', 'autosmidsize',
       'entertainmenttv', 'autoslosangeles', 'celebhub'], dtype=object)

In [11]:
news["subcategory"].value_counts()

subcategory
newsus                    6564
football_nfl              5420
newspolitics              2826
newscrime                 2254
weathertopstories         2047
                          ...
newsvideo                    1
travel                       1
lifestylehoroscopefish       1
baseball                     1
celebhub                     1
Name: count, Length: 264, dtype: int64

In [12]:
news["subcategory"].nunique()

264

In [13]:
row = behaviors.iloc[30]

print("User:", row["user_id"])
print("History:", row["history"])
print("Impressions:", row["impressions"])

User: U85394
History: N46911 N1150 N8129 N53387 N38118 N49995 N55189 N10059 N33683 N871 N33247 N26978 N20997 N16290 N44237 N58641 N57571 N43725 N19994 N4536 N54822 N64314 N1966 N14185 N35552 N13137 N5241 N11101 N46392 N59704 N53033 N9120 N37811 N55148 N4069 N16423 N41997 N21493 N34649 N54625 N22753 N3057 N712 N6466 N34105 N12349 N34394 N61267 N4166 N44885 N41375 N52875 N15765 N14452 N13138 N13429 N37663 N51705 N32194 N49040
Impressions: N61022-0 N49279-1 N44651-0

In [14]:
row = behaviors.iloc[323]

print("User:", row["user_id"])
print("History:", row["history"])
print("Impressions:", row["impressions"])

User: U54138
History: N13186 N6552 N50155 N38629 N33713 N879 N47558 N42989 N64777 N32643 N9824 N4830 N27676 N2229 N49745 N871 N53900 N26642 N27612 N16233 N44454 N60050 N18663 N21561 N63906 N10865 N40912 N56109 N49229 N18030 N33276 N18094 N6156 N53033 N56486 N53531 N45794 N17966 N37915 N46513 N4593 N477 N64955 N5184 N58841 N8917 N6864 N58090 N16715 N40692 N61196 N45999 N56638 N44796 N13057 N13374 N20708 N56240 N31801 N63180 N11005 N54655 N23105 N306 N47719 N41375 N60491 N28702 N43142 N5217 N55556 N38105 N20342 N62058 N8148 N22816 N2735 N40509 N15676 N25785
Impressions: N20076-0 N47061-0 N60992-0 N36659-0 N42977-1 N37905-0 N13579-0 N22230-0 N45266-0 N38159-0 N62128-1 N28213-0

In [15]:
def add_temporal_context(df):
    df['time'] = pd.to_datetime(df['time'])

    hour = df['time'].dt.hour
    df['hour_sin'] = np.sin(2 * np.pi * hour / 24.0)
    df['hour_cos'] = np.cos(2 * np.pi * hour / 24.0)

    day = df['time'].dt.dayofweek
    df['day_sin'] = np.sin(2 * np.pi * day / 7.0)
    df['day_cos'] = np.cos(2 * np.pi * day / 7.0)

    return df

In [16]:
behaviors = add_temporal_context(behaviors)

In [17]:
def parse_impressions(impressions):
    items = impressions.split()
    data = []
    
    for item in items:
        news_id, label = item.split("-")
        data.append((news_id, int(label)))
        
    return data

# test
print(parse_impressions(row["impressions"]))

[('N20076', 0), ('N47061', 0), ('N60992', 0), ('N36659', 0), ('N42977', 1), ('N37905', 0), ('N13579', 0), ('N22230', 0), ('N45266', 0), ('N38159', 0), ('N62128', 1), ('N28213', 0)]

In [18]:
processed_behaviour = []

for _, row in behaviors.iterrows():
    history = row["history"]
    
    if pd.isna(history):
        continue
        
    parsed = parse_impressions(row["impressions"])
    
    for news_id, label in parsed:
        processed_behaviour.append({
            "user_id": row["user_id"],
            "history": history,
            "news_id": news_id,
            "label": label
        })

df = pd.DataFrame(processed_behaviour)
print(df.head())

  user_id                                            history news_id  label
0  U13740  N55189 N42782 N34694 N45794 N18445 N63302 N104...  N55689      1
1  U13740  N55189 N42782 N34694 N45794 N18445 N63302 N104...  N35729      0
2  U91836  N31739 N6072 N63045 N23979 N35656 N43353 N8129...  N20678      0
3  U91836  N31739 N6072 N63045 N23979 N35656 N43353 N8129...  N39317      0
4  U91836  N31739 N6072 N63045 N23979 N35656 N43353 N8129...  N58114      0

In [19]:
#Remove empty history
df = df[df["history"].notna()]

In [20]:
df["history"] = df["history"].apply(lambda x: x.split())

In [ ]:
df.head()

,user_id,history,news_id,label,category
0,U13740,"[N55189, N42782, N34694, N45794, N18445, N6330...",N55689,1,sports
1,U13740,"[N55189, N42782, N34694, N45794, N18445, N6330...",N35729,0,news
2,U91836,"[N31739, N6072, N63045, N23979, N35656, N43353...",N20678,0,sports
3,U91836,"[N31739, N6072, N63045, N23979, N35656, N43353...",N39317,0,news
4,U91836,"[N31739, N6072, N63045, N23979, N35656, N43353...",N58114,0,autos

In [ ]:
# Select useful columns
news_clean = news[["news_id", "category", "subcategory", "title", "abstract"]].copy()

# Handle missing values
news_clean["category"] = news_clean["category"].fillna("unknown")
news_clean["subcategory"] = news_clean["subcategory"].fillna("unknown")
news_clean["title"] = news_clean["title"].fillna("")
news_clean["abstract"] = news_clean["abstract"].fillna("")

# Remove duplicates
news_clean = news_clean.drop_duplicates(subset="news_id")

# Reset index
news_clean = news_clean.reset_index(drop=True)

print(news_clean.head())
print("Shape:", news_clean.shape)

  news_id   category      subcategory  \
0  N55528  lifestyle  lifestyleroyals
1  N19639     health       weightloss
2  N61837       news        newsworld
3  N53526     health           voices
4  N38324     health          medical

                                               title  \
0  The Brands Queen Elizabeth, Prince Charles, an...
1                      50 Worst Habits For Belly Fat
2  The Cost of Trump's Aid Freeze in the Trenches...
3  I Was An NBA Wife. Here's How It Affected My M...
4  How to Get Rid of Skin Tags, According to a De...

                                            abstract
0  Shop the notebooks, jackets, and more that the...
1  These seemingly harmless habits are holding yo...
2  Lt. Ivan Molchanets peeked over a parapet of s...
3  I felt like I was a fraud, and being an NBA wi...
4  They seem harmless, but there's a very good re...
Shape: (51282, 5)

In [ ]:
behaviors_clean = df.copy()


# Remove rows with empty history (optional but recommended)
behaviors_clean = behaviors_clean[behaviors_clean["history"].notna()]


# Reset index
behaviors_clean = behaviors_clean.reset_index(drop=True)

print(behaviors_clean.head())
print("Shape:", behaviors_clean.shape)

  user_id                                            history news_id  label  \
0  U13740  [N55189, N42782, N34694, N45794, N18445, N6330...  N55689      1
1  U13740  [N55189, N42782, N34694, N45794, N18445, N6330...  N35729      0
2  U91836  [N31739, N6072, N63045, N23979, N35656, N43353...  N20678      0
3  U91836  [N31739, N6072, N63045, N23979, N35656, N43353...  N39317      0
4  U91836  [N31739, N6072, N63045, N23979, N35656, N43353...  N58114      0

  category
0   sports
1     news
2   sports
3     news
4    autos
Shape: (5723002, 5)

In [ ]:
news_clean.to_csv("data/cleaned/news_clean.csv", index=False)
behaviors_clean.to_csv("data/cleaned/behaviors_clean.csv", index=False)